stages:

  load_data:
    cmd: python src/load_data.py
    deps:
    - data/raw
    outs:
    - data/processed:
        cache: true
        persist: true
    - data/processed_files.txt:
        cache: false
        persist: true
    always_changed: true

  prepare_data:
    cmd: python src/prepare_data.py
    deps:
    - src/prepare_data.py
    - data/processed_files.txt
    outs:
    - data/features.csv

  train:
    cmd: |
      mkdir -p models/checkpoints models/checkpoints_resume
      python src/train.py --resume_checkpoint ${train.resume_checkpoint}
    deps:
    - data/features.csv
    outs:
    - models/checkpoints
    - models/checkpoints_resume:
        persist: true
    - models/model.ckpt:
        persist: true
        cache: false

artifacts:
  best:
    path: models/model.ckpt
    type: model
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
