stages:

  load_data:
    cmd: python src/load_data.py
    deps:
    - data/raw
    outs:
    - data/processed:
        cache: true
        persist: true
    - data/processed_files.txt:
        cache: false
        persist: true
    always_changed: true

  prepare_data:
    cmd: python src/prepare_data.py
    deps:
    - src/prepare_data.py
    - data/processed_files.txt
    outs:
    - data/features.csv

  train:
    cmd: python src/train.py
    deps:
    - data/features.csv
    outs:
    - mnt/disk1/checkpoints
    - models/model.ckpt:
        persist: true
        cache: false

plots:
- dvclive/plots/metrics:
    x: step
metrics:
- dvclive/metrics.json
params:
- dvclive/params.yaml
artifacts:
  best:
    path: models/model.ckpt
    type: model
